### ISSUE TITLE
failure to raise DisambiguationError for "Leaching" page on Wikipedia

### ISSUE THREAD

**Issue by lebedov** [barrust/mediawiki#35]
Using pymediawiki 0.3.15 with Python 3.6.3 on Linux, I observed the following error when attempting to access the disambiguation page for "Leaching" on Wikipedia.

    python -c "import mediawiki; wikipedia=mediawiki.MediaWiki(); wikipedia.page('Leaching')"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/mediawiki/mediawiki.py", line 731, in page
        preload=preload)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/mediawiki/mediawikipage.py", line 72, in __init__
        self.__load(redirect=redirect, preload=preload)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/mediawiki/mediawikipage.py", line 532, in __load
        self._raise_disambiguation_error(page, pageid)
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/mediawiki/mediawikipage.py", line 569, in _raise_disambiguation_error
        one_disambiguation['title'] = item[0]['title']
      File "/home/lebedov/miniconda3/lib/python3.6/site-packages/bs4/element.py", line 1011, in __getitem__
        return self.attrs[key]
    KeyError: 'title'

Relatedly, wikipedia 1.4.0 correctly raises a `DisambiguationError` exception for the above.

**Comment by barrust** [comment]
@lebedov : this should be resolved in version 0.3.16. You can get the latest using pip:
```
pip install pymediawiki --upgrade
```

Please let me know how the pymediawiki is working for you and if you run into any other issues!

**Comment by lebedov** [comment]
Looks good. Thanks for the quick fix!

**Comment by awbirdsall** [comment]
Hi, thanks for all your work on this project! It has been very handy.

I think there might still be a small bug associated with this issue/associated PR.

https://github.com/barrust/mediawiki/commit/243e7a0fca6471ce550cab82306b7693b410deec#diff-c017063330dbc8ad5b88a8c5049c389bR568

Following the link above to the code raising a DisambiguationError, I think the new line `if item and hasattr(item, 'title'):` will always evaluate to `False` because `item` is what's returned by a beautifulsoup `find_all()` call, which is a list. Should it be `if item and hasattr(item[0], 'title'):` instead?

This led to some confusion on my end, because I've been always seeing the `disambiguation['title']` equal the full text of the `li` rather than just the title of the link...

**Comment by barrust** [comment]
@awbirdsall can you provide me an example where this is not working correctly? For the pages that I am testing I am seeing what I expected to see. Thanks!

**Comment by awbirdsall** [comment]
@barrust : here's an example for "Lincoln Museum" (https://en.wikipedia.org/wiki/Lincoln_Museum):

```
from mediawiki import MediaWiki, DisambiguationError
wikipedia = MediaWiki()

try:
    p = wikipedia.page("Lincoln Museum")
except DisambiguationError as d:
    print(d.details[5]['title'])
    print(d.details[5]['description'])
```

I'd expect the `title` here to be only "Ford's Theatre" since that's the title of the link, but instead the `title` is the same as the full `description`.

```
In [8]: print(mediawiki.__version__)                                                                               
0.6.0
```
